### ISSUE TITLE
numOutVars in Example/Bayesian_Calibration.bat

### ISSUE THREAD

**Issue by miwamasa** [Argonne-National-Laboratory/BCUS#1]
In the batch file some options seems wrong.

It seems that  "--numOutVars 2" is necessary because Utiiity.csv ha two colums 
   ie. Electricity Consumption [ J ],	Natural Gas [ J ]
 
-org--
ruby -S BC.rb ExampleBuilding.osm Weather_USA_PA_Willow.Grove.NAS.724086_TMY3.epw --numMCMC 200 --numBurnin 3  --noRunCal --priorsFile Prior.csv

**Comment by muehleisen** [comment]
Thanks for finding the error.  Please feel free to correct the batch file and make a pull request.

While the repository is publicly available, we haven't advertised it to the larger community because we are still finding errors like this.

**Comment by miwamasa** [comment]
Hello ANL friends,

   Quite unfortunately, I am inside the corporate firewall, I am not officially allowed direct contribution( putting files to the public repositories)..

  So for the meantime, if I find any bugs, I will report them  to the “issue” thread.

The reason I have encountered with your repository is that,

  I have been interested Bayesian calibration, and my colleague Dr. Otsuki had attended SimBuild2016 and get some information on BC from ANL person. So I am watching ANL activates on BC.

Thank you for your reply and please keep in touch.
Mikito
--
Toshiba R&D Center, Japan
