### ISSUE TITLE
R file extensions for unix environment

### ISSUE THREAD

**Issue by miwamasa** [Argonne-National-Laboratory/BCUS#2]
R files such as  gendist.r  , graphPosteriors.r  are not recogonized in UNIX(ubuntu) enviroment.

Upper/Lower charactors are distinguished in UNIX.

by renaming them  *.r -> *.R , it worked in my ubuntu system.

**Comment by muehleisen** [comment]
Thanks for letting us know.   We'll try to update the documentation to make it clear that some people might need to rename.  Most of our development is on windows systems.  We try to check that things run on OSX and Ubuntu, but sometimes we haven't caught all the bugs.
