### ISSUE TITLE
OpenStudio 2.1.0 migration

### ISSUE THREAD

**Issue by miwamasa** [Argonne-National-Laboratory/BCUS#7]
NREL just released OpenStudio 2.1.0.

 https://github.com/NREL/OpenStudio/releases/tag/v2.1.0

It says,
 
 

> However, the RunManager, Analysis, Project, and AnalysisDriver namespaces were completely removed. The CLI and OSW format replace the functionality of RunManager. 

Do you have any plan to migrate to OpenStudio2.1 enviroment?

FYI:
 The running osm in the new CLI/OSW scheme might look like this,

```
for k in 2..samples[0].length-1
  osw_path =  "#{path}/in.osw"
  osw_path = File.absolute_path(osw_path)
  workflow = OpenStudio::WorkflowJSON.new
  workflow.setSeedFile(File.absolute_path("#{path}/PreRuns_Models/Sample#{k-1}.osm"))
  workflow.setWeatherFile(File.absolute_path(epw_path))
  workflow.saveAs(osw_path)

  cli_path = OpenStudio.getOpenStudioCLI
  cmd = "\"#{cli_path}\" run -w \"#{osw_path}\""
  puts cmd
  system(cmd)
end

```
This is not as sophisticated as its predecessor(RunManager). I beleieve OpenStudio-server which is used in the new PAT(Parametric Analysis Tool) might be a good replacement to the RunManager.

**Comment by muehleisen** [comment]
Yes we have plans to migrate to the OpenStudio 2.1 environment.  I want to do my updates for 1.14 (the last of the "old" versions of OpenStudio and then updating things to work with 2.1 including dealing with the removal of runmanager.  I would like to integrate better with PAT and the OpenStudio Server.

Thanks for asking.

**Comment by miwamasa** [comment]
Thank you for your reply. Looking forward to seeing your progress.
